Update dependency check version, add new steps to pipeline for new DB
hmcts/cnp-owaspdependencycheck-update pull request #31
Opened 2023-11-27 11:47 UTC by reespozzi

Updating to add new stages that use the newly created DB for dependency check update
Added new gradle file with latest version of dependency check so the old DBs are not corrupted/broken in anyway
Added secret pulling for new API key from NVD

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-11-27 11:54 UTC, timja requested changes

2023-11-27 11:54 UTC, timja commented on build-v6-new.gradle
never use new in a file name

build-v9.gradle would be more appropriate

2023-11-27 13:50 UTC, timja approved these changes

2023-12-05 10:15 UTC, adusumillipraveen approved these changes

2023-12-05 10:17 UTC, merged